# Generated by Django 3.1.6 on 2021-04-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20210429_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='basic_app.school'),
        ),
    ]
